// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DataHubDemo.Features.Modules.Product
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Share the product with other company and view the shared product examples", new string[] {
            "Chrome",
            "Datahub-QA",
            "Admin"}, SourceFile="Features\\Modules\\Product\\ProductViewUseFeature.feature", SourceLine=1)]
    public partial class ShareTheProductWithOtherCompanyAndViewTheSharedProductExamplesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ProductViewUseFeature.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Share the product with other company and view the shared product examples", null, ProgrammingLanguage.CSharp, new string[] {
                        "Chrome",
                        "Datahub-QA",
                        "Admin"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ShareTheProductWithOtherCompany(string @case, string loginCompanyName, string gTIN, string sharedompanyName, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Share the product with other company", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
    testRunner.Given(string.Format("a user login to datahub with company  {0}", loginCompanyName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
  testRunner.Given("navigate to product manage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
    testRunner.Given("navigate to InUse", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
testRunner.Given(string.Format("serach the {0} and select the product", gTIN), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
    testRunner.And("Click on sharing tab and click AddButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
    testRunner.When(string.Format("the user share the selected product with company {0}", sharedompanyName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
    testRunner.Then("the product is shared with the selected company", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Share the product with other company, product1", new string[] {
                "source:ProductViewUSeExamples.xlsx"}, SourceLine=1)]
        public virtual void ShareTheProductWithOtherCompany_Product1()
        {
#line 4
this.ShareTheProductWithOtherCompany("product1", "Medical Devices R Us", "816471025448", "Amalgamated Hospital Purchasing", new string[] {
                        "source:ProductViewUSeExamples.xlsx"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Share the product with other company, prdocut2", new string[] {
                "source:ProductViewUSeExamples.xlsx"}, SourceLine=1)]
        public virtual void ShareTheProductWithOtherCompany_Prdocut2()
        {
#line 4
this.ShareTheProductWithOtherCompany("prdocut2", "Medical Devices R Us", "10816471025575", "Amazon Corporate LLC", new string[] {
                        "source:ProductViewUSeExamples.xlsx"});
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
